name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '1 10 * * 5'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          feed_list: "https://nekrasovp.github.io/feeds/blog.atom.xml"
          max_post_count: "5"
          template: "$newline- [$title]($url)"
          committer_username: "Nekrasovp"
          committer_email: "7581719+nekrasovp@users.noreply.github.com"
